### ISSUE TITLE
Better README.md

### ISSUE THREAD

**Issue by lfarah** [Isuru-Nanayakkara/InstagramAuthViewController#1]
Hey @Isuru-Nanayakkara, your library is really interesting.

The only problem I found was the `README.md`, which needs a little bit of more information
I created this [iOS Open source Readme Template](https://github.com/awesome-labs/iOS-readme-template) so you can take a look on how to better organize.
If you want, I can help you to do it

What are your thoughts?

**Comment by Isuru-Nanayakkara** [comment]
Hi @lfarah,

Thanks for taking your time to check it out. I agree, the README indeed needs to be improved. I just created this library as a side project and a learning experience so I didn't think anyone would come across it until it got featured in the Indie iOS developer newsletter.

I will update it within today.

**Comment by Isuru-Nanayakkara** [comment]
Updated the README according to the template you linked. It's pretty neat. Thanks!
